### ISSUE TITLE
DME Frequency

### ISSUE THREAD

**Issue by ovord** [openflightmaps/ofmx#10]
@svoop 

Can we leave the valFreq? even if the channel is used internally, you set the freq on the dme receiver in the cockpit

**Comment by svoop** [comment]
LF AIP (and maybe others) list channels only. However, since every channel can be mapped to one frequency and vice versa, we could use such a map to always feature both for DME and TACAN.

I'll revise the XSD to make both channel and frequency mandatory.

**Comment by svoop** [comment]
@ovord The channel [maps to two frequencies](http://www.e-haf.org/PublicFTP/320/UPLOAD_FOLDER/Charts/VOR%20Frequencies%20to%20TACAN%20Channel%20list.pdf), transmission and reception. If the DME receiver is not working with channels, I guess the reception frequency is the one you're interested in, correct?

**Comment by svoop** [comment]
@ovord 

Or maybe you refer to the "ghost frequency"? As a glider, I have no practical experience with IFR instruments, so this is a little guess work here:

Usually, DME (or TACAN) are collocated with VOR and since the VOR frequency maps to a DME channel and vice versa, it should be sufficient to set the VOR frequency on the receiver in the cockpit to implicitly set the DME channel as well.

However, DME *not* collocated with VOR technically require a receiver to accept the DME channel. In the interest of a uniform user interface, my guess is that receivers always require to set the VOR frequency to configure the DME – even if there is not VOR present at all.

AIXM features a property `DME#valGhostFreq` (and `DME#valGhostUom` for the unit). It's description is not very clear, but it seems to be the frequency of the virtual (aka: non-existing) VOR:

<img width="591" alt="screen shot 2018-04-29 at 10 19 46" src="https://user-images.githubusercontent.com/7255/39404679-0e860fca-4b98-11e8-85e8-861045ab6f5c.png">

This ghost frequency can be derived from the DME channel by use [mapping table mentioned above](http://www.e-haf.org/PublicFTP/320/UPLOAD_FOLDER/Charts/VOR%20Frequencies%20to%20TACAN%20Channel%20list.pdf).

If the ghost frequency is what you need, then there are two possible solutions:

1. We leave the schema as is: The importer takes the mandatory channel, looks up the ghost frequency from the table and writes both to the db. The exporter then writes both the mandatory channel and the optional ghost frequency.
2. We change the schema to make the ghost frequency mandatory.

Despite the additional coding necessary on the OFM end, I'm in favor of solution 1 because it rules out channel/ghost frequency disagreements e.g. if the ghost frequency is misprinted on the AIP or has been wrongly entered by a contributor.

**Comment by svoop** [comment]
The DME properties `Dme->valGhostFreq` and `Dme->uomGhostFreq` are documented now. TACAN are identical to DME for civilian aircraft, however, AIXM does not feature ghost frequencies for them. With comit c7e5ed36 OFMX now does: `Tcn->valGhostFreq` and `Tcn->uomGhostFreq`.
